export interface IbackApi{
    
        PKID: string | number|null,
        ConnectPRID:string | number|null,
        Type_Of_Buy: string|null,
        PrepaidOrCapitalEquipment:
          string|null,
        EHS: boolean|null,
        Title:
          string|null,
        RequestFor: string|null,
        Type_Of_Order: string|null,
        Order_Amount:number | null,
        CIP_Number:string| null,
        UFID: string|null,
        Supplier_Account_Number: string|null,
        Supplier_Name: string|null,
        Supplier_Address: string|null,
        Supplier_City: string|null,
        Supplier_State: string|null,
        Supplier_Zip: string|null,
        Supplier_Country: string|null,
        Manager: string|null,
        Manager1: string|null,
        Manager2: string|null,
        Manager3: string|null,
        GL_Account: string|null,
        Status: string|null,
        TaskCreatedFor: null,
        ApprovalInstance: number|null,
        Comments: string|null,
        Cost_Center: number|null,
        Location: string|null,
        IsDeleted: null,
        Special_Instructions: string|null,
        Shipping_Name: string|null,
        Shipping_Street: string|null,
        Shipping_Postal_Code: string|null,
        Shipping_Location: string|null,
        Shipping_Region: string|null,
        Shipping_Country: string|null,
        Shipping_ContactPhone: string|null,
        OldReqId: number|null,
        SAPPRId: string|null,
        LastWorkflowRun: string|null,
        CurrentApprovalStep: string|null,
        ManagerLevel: number|null,
        FinalApprovalDate: string|null,
        IsOtherCC: boolean|null,
        IsCFOApproved: boolean|null,
        CFO: string|null,
        AllApprovers: string|null,
        CreateDate: string|null,
        LastStatus: string|null,
        AllManagers: string|null,
        JLReminderCount: number|null,
        FIReminderCount: number|null,
        AesyntPRType: string|number|null,
        PONumber: string|null,
        IsCompleted: boolean|null,
        Company: string|null,
        ProjectNumber: string|null,
        ActCostCenter:number|null,
        CompanyCode:string|null,
        FromCurrency:string|null,
        ToCurrency: string|null,
        RequesterCurrency: string|null,
        ExchangeRate:string|number|null,
        ExchangeRateV: string|null,
        ExchangeRateDate: string|null,
        ConvertedDollerAmount: number|null,
        CountryKey: string|null,
        HRADCompanyCode:string|null,
        QuickbookPO: string|null,
        CCDescription: string|null,
        IsProjectPR: boolean|null,
        ProjectDepartment: string|null,
        ProjectCode: string|null,
        Created: string| null,
        CreatedBy: string|null,
        Modified: string|null,
        ModifiedBy: string|null,
        PRNumber: string|null,
        DWCreateDate: string|null,
        PRId: string|null,
        OldAllApprovers: string|null,
        OldAllManagers: string|null,
        OldCFO: string|null,
        OldCreatedBy: string|null,
        OldManager: string|null,
        OldManager1: string|null,
        OldManager2: string|null,
        OldManager3: string|null,
        OldModifiedBy: string|null,
        OldRequestFor: string|null,
        OldTaskCreatedFor: string|null,
      
} 