export class IPRItem {
  ActCostCenter: number;
  AesyntPRType :string;
  AllApproversId: number;
  AllApproversStringId: number;
  AllManagersId: number;
  AllManagersStringId: number;
  ApprovalInstance: number;
  Attachments: boolean;
  AuthorId: number;
  CCDescription :string;
  CFOId: number;
  CFOStringId :string;
  CIP_Number: number;
  Comments :string;
  Company :string;
  CompanyCode :string;
  ComplianceAssetId: number;
  ContentTypeId :string;
  ConvertedDollerAmount: number;
  Cost_Center: number;
  CountryKey :string;
  CreateDate: Date;
  Created :string;
  CurrentApprovalStep :string;
  EHDelegationCount: number;
  EHS: boolean;
  EditorId: number;
  ExchangeRate: number;
  ExchangeRateDate: Date;
  ExchangeRateV: number;
  FIDelegationCount: number;
  FIReminderCount: number;
  FileSystemObjectType: number;
  FinalApprovalDate: Date;
  FromCurrency :string;
  GL_Account :string;
  GUID :string;
  HRADCompanyCode :string;
  HSRIPO :string;
  ID: number;
  IsCFOApproved: boolean;
  IsCompleted: boolean;
  IsITVPApproved: boolean;
  IsOtherCC: boolean;
  IsProjectPR: boolean;
  JLReminderCount: number;
  LastStatus :string;
  LastWorkflowRun: Date;
  Location :string;
  Manager1Id: number;
  Manager1StringId :string;
  Manager2Id: number;
  Manager2StringId :string;
  Manager3: any;
  ManagerId: number;
  ManagerLevel :string;
  ManagerStringId :string;
  Modified: Date;
  OldReqId: number;
  Order_Amount: number;
  PONumber :string;
  PRID: number;
  PR_Created_For_Self: boolean;
  PrepaidOrCapitalEquipment :string;
  ProjectCode :string;
  ProjectDepartment :string;
  ProjectNumber :string;
  QuickbookPO :string;
  RequestForId: number;
  RequestForStringId :string;
  RequesterCurrency :string;
  SAPPOBalance: number;
  SAPPOEmailCount: number;
  SAPPONO: number;
  SAPPRId: number;
  SFADate: Date;
  Shipping_ContactPhone :string;
  Shipping_Country :string;
  Shipping_Location :string;
  Shipping_Name :string;
  Shipping_Postal_Code :string;
  Shipping_Region :string
  Shipping_Street :string
  Special_Instructions :string;
  Status :string;
  Supplier_Account_Number :string;
  Supplier_Address :string;
  Supplier_City :string;
  Supplier_Country :string;
  Supplier_Name :string;
  Supplier_State :string;
  Supplier_Zip :string;
  TaskCreatedForId: number;
  TaskCreatedForStringId :string;
  ThreeFortyBPO: string;
  Title :string;
  ToCurrency :string;
  Type_Of_Buy :string;
  Type_Of_Order :string;
  UFID: number;
  submit_requestors_cost_center :string;



  constructor() {
    this.ActCostCenter = 0;
    this.AesyntPRType = "";
    this.AllApproversId = 0;
    this.AllApproversStringId = 0;
    this.AllManagersId = 0;
    this.AllManagersStringId = 0;
    this.ApprovalInstance = 0;
    this.Attachments = true;
    this.AuthorId = 0;
    this.CCDescription = "";
    this.CFOId = 0;
    this.CFOStringId = "";
    this.CIP_Number = 0;
    this.Comments = "";
    this.Company = "";
    this.CompanyCode = "";
    this.ComplianceAssetId = 0;
    this.ContentTypeId = "";
    this.ConvertedDollerAmount = 0;
    this.Cost_Center = 0;
    this.CountryKey = "";
    this.CreateDate = new Date();
    this.Created = "";
    this.CurrentApprovalStep = "";
    this.EHDelegationCount = 0;
    this.EHS = true;
    this.EditorId = 0;
    this.ExchangeRate = 0;
    this.ExchangeRateDate = new Date();
    this.ExchangeRateV = 0;
    this.FIDelegationCount = 0;
    this.FIReminderCount = 0;
    this.FileSystemObjectType = 0;
    this.FinalApprovalDate = new Date();
    this.FromCurrency = "";
    this.GL_Account = "";
    this.GUID = "";
    this.HRADCompanyCode = "";
    this.HSRIPO = "";
    this.IsCFOApproved = true;
    this.IsCompleted = true;
    this.IsITVPApproved = true;
    this.IsOtherCC = true;
    this.IsProjectPR = true;
    this.JLReminderCount = 0;
    this.LastStatus = "";
    this.LastWorkflowRun = new Date();
    this.Location = "";
    this.Manager1Id = 0;
    this.Manager1StringId = "";
    this.Manager2Id = 0;
    this.Manager2StringId = "";
    this.Manager3 = null;
    this.ManagerId = 0;
    this.ManagerLevel = "";
    this.ManagerStringId = "";
    this.Modified = new Date();
    this.OldReqId = 0;
    this.Order_Amount = 0;
    this.PONumber = "";
    this.PRID = 0;
    this.PR_Created_For_Self = true;
    this.PrepaidOrCapitalEquipment = "";
    this.ProjectCode = "";
    this.ProjectDepartment = "";
    this.ProjectNumber = "";
    this.QuickbookPO = "";
    this.RequestForId = 0;
    this.RequestForStringId = "";
    this.RequesterCurrency = "";
    this.SAPPOBalance = 0;
    this.SAPPOEmailCount = 0;
    this.SAPPONO = 0;
    this.SAPPRId = 0;
    this.SFADate = new Date();
    this.Shipping_ContactPhone = "";
    this.Shipping_Country = "";
    this.Shipping_Location = "";
    this.Shipping_Name = "";
    this.Shipping_Postal_Code = "";
    this.Shipping_Region = ""
    this.Shipping_Street = ""
    this.Special_Instructions = "";
    this.Status = "";
    this.Supplier_Account_Number = "";
    this.Supplier_Address = "";
    this.Supplier_City = "";
    this.Supplier_Country = "";
    this.Supplier_Name = "";
    this.Supplier_State = "";
    this.Supplier_Zip = "";
    this.TaskCreatedForId = 0;
    this.TaskCreatedForStringId = "";
    this.ThreeFortyBPO = "";
    this.Title = "";
    this.ToCurrency = "";
    this.Type_Of_Buy = "";
    this.Type_Of_Order = "";
    this.UFID = 0;
    this.submit_requestors_cost_center = "";

  }


}